

export enum UserRole {
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  USER = 'USER',
  GUEST = 'GUEST'
}

export interface User {
  id: string;
  username: string;
  password?: string;
  role: UserRole;
  avatar?: string;
  cover?: string;
  bio?: string;
  facebook?: string;
  whatsapp?: string;
  location?: string;
}

export interface DynamicPage {
  id: string;
  title: string;
  slug: string;
  content: string;
  status: 'published' | 'draft';
  createdAt: number;
}

export interface SiteConfig {
  siteName: string;
  siteTagline: string;
  footerText: string;
  themeGradient: string;
  showClock: boolean;
  enableAiSync: boolean;
  enableExamSystem: boolean;
  enableJobBoard: boolean;
  headerScripts?: string;
  footerScripts?: string;
  seoKeywords?: string;
  activeFeatures: string[]; // List of AI-installed modules
}

export interface Post {
  id: string;
  type: 'sms' | 'story' | 'job';
  title?: string;
  content: string;
  image?: string; 
  imagePrompt?: string;
  authorId: string;
  authorName: string;
  timestamp: number;
  likes: number;
  comments: Comment[];
  category?: string;
  url?: string; 
  sticker?: string;
}

export interface Comment {
  id: string;
  userId: string;
  username: string;
  text: string;
  timestamp: number;
}

export interface MCQQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

/**
 * Interface for Job Circulars generated by AI or fetched from sync
 */
export interface JobCircular {
  id?: string;
  company: string;
  position: string;
  deadline: string;
  location: string;
  link: string;
  type: string;
  industry: string;
}
